"use client";

import { checkInAction, checkOutAction, markRoomReadyAction } from "@/app/internal/(dashboard)/operations/actions";
import { ConfirmAction } from "@/components/ui/confirm-action";
import type { DailyOperations, OperationBooking } from "@/lib/api/types";
import { localize, useLocale } from "@/lib/locale";
import Link from "next/link";

const paymentTone: Record<string, string> = {
  paid: "bg-[#e3f1e8] text-[#285d3d]",
  partial: "bg-[#fff2d9] text-[#765017]",
  pending_verification: "bg-[#e6eef8] text-[#234e7d]",
  unpaid: "bg-surface-high text-muted",
  failed: "bg-[#ffdad6] text-[#93000a]",
  refunded: "bg-surface-high text-muted",
};

function BookingRow({ booking, kind, canUpdate }: { booking: OperationBooking; kind: "arrival" | "departure"; canUpdate: boolean }) {
  const locale = useLocale();
  const date = new Intl.DateTimeFormat(locale === "en" ? "en-US" : "id-ID", { day: "numeric", month: "short", year: "numeric" });
  const formatDate = (value: string) => date.format(new Date(`${value}T00:00:00`));
  const completed = kind === "arrival" ? booking.status === "checked_in" : booking.status === "checked_out";
  const timestamp = kind === "arrival" ? booking.checked_in_at : booking.checked_out_at;
  const time = timestamp ? new Intl.DateTimeFormat(locale === "en" ? "en-US" : "id-ID", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Makassar" }).format(new Date(timestamp)) : null;

  return <article className="grid gap-5 px-5 py-6 transition-colors hover:bg-surface-low/60 sm:px-6 lg:grid-cols-[minmax(0,1.3fr)_minmax(150px,.7fr)_auto] lg:items-center">
    <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/internal/bookings/${booking.id}`} className="font-semibold underline decoration-transparent underline-offset-4 hover:text-secondary hover:decoration-current">{booking.guest_name}</Link>{completed && <span className="rounded-full bg-[#e3f1e8] px-2.5 py-1 text-[10px] font-semibold tracking-[0.06em] text-[#285d3d] uppercase">{kind === "arrival" ? localize(locale, "Sudah check-in", "Checked in") : localize(locale, "Sudah check-out", "Checked out")}</span>}</div><p className="mt-1 truncate text-sm text-muted">{booking.booking_code} · {booking.guest_phone}</p><p className="mt-2 text-sm"><span className="font-semibold">{booking.room.name}</span><span className="text-muted"> · {booking.guest_count} {localize(locale, "tamu", booking.guest_count === 1 ? "guest" : "guests")}</span></p></div>
    <div><p className="text-[10px] font-semibold tracking-[0.08em] text-muted uppercase">{kind === "arrival" ? "Check-in" : "Check-out"}</p><p className="mt-2 text-sm font-semibold tabular-nums">{time ? `${formatDate(kind === "arrival" ? booking.check_in : booking.check_out)} · ${time}` : formatDate(kind === "arrival" ? booking.check_in : booking.check_out)}</p>{kind === "arrival" && <span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold tracking-[0.05em] uppercase ${paymentTone[booking.payment.status]}`}>{locale === "en" ? ({ paid: "Paid", partial: "Partially paid", pending_verification: "Pending verification", unpaid: "Unpaid", failed: "Failed", refunded: "Refunded" }[booking.payment.status]) : booking.payment.status_label}</span>}</div>
    <div className="flex flex-wrap items-center gap-3 lg:min-w-40 lg:justify-end">{completed ? <Link href={`/internal/bookings/${booking.id}`} className="inline-flex min-h-11 items-center text-sm font-semibold text-secondary underline-offset-4 hover:underline">{localize(locale, "Lihat detail", "View details")}</Link> : kind === "arrival" ? <>{booking.can_check_in && canUpdate ? <ConfirmAction action={checkInAction.bind(null, booking.id)} trigger={localize(locale, "Proses check-in", "Check in")} title={localize(locale, `Check-in ${booking.guest_name}?`, `Check in ${booking.guest_name}?`)} description={localize(locale, `Pastikan identitas tamu, pembayaran, dan kesiapan ${booking.room.name} sudah diperiksa.`, `Confirm the guest identity, payment, and readiness of ${booking.room.name}.`)} confirmLabel={localize(locale, "Ya, catat check-in", "Yes, check in")} tone="primary" triggerVariant="primary" reason={{ label: localize(locale, "Catatan kedatangan · opsional", "Arrival note · optional"), placeholder: localize(locale, "Contoh: menyerahkan satu kunci", "Example: handed over one key") }} /> : <div className="lg:max-w-52"><p className="text-xs leading-5 text-muted">{localize(locale, booking.action_block_reason ?? "Aksi belum tersedia", booking.action_block_reason === "Tanggal check-in belum tiba" ? "Check-in date has not arrived" : "Payment is not fully paid and verified")}</p>{booking.payment.id && <Link href={`/internal/payments/${booking.payment.id}`} className="mt-2 inline-flex text-sm font-semibold text-secondary underline-offset-4 hover:underline">{localize(locale, "Tinjau pembayaran", "Review payment")}</Link>}</div>}</> : booking.can_check_out && canUpdate ? <ConfirmAction action={checkOutAction.bind(null, booking.id)} trigger={localize(locale, "Proses check-out", "Check out")} title={localize(locale, `Check-out ${booking.guest_name}?`, `Check out ${booking.guest_name}?`)} description={localize(locale, `${booking.room.name} akan otomatis masuk antrean pembersihan.`, `${booking.room.name} will automatically enter the cleaning queue.`)} confirmLabel={localize(locale, "Ya, catat check-out", "Yes, check out")} tone="primary" triggerVariant="primary" reason={{ label: localize(locale, "Catatan kondisi · opsional", "Condition note · optional"), placeholder: localize(locale, "Kerusakan, barang tertinggal, atau kebutuhan pembersihan", "Damage, lost items, or cleaning needs") }} /> : null}</div>
  </article>;
}

function Empty({ children }: { children: string }) { return <p className="px-6 py-12 text-center text-sm leading-6 text-muted">{children}</p>; }

export function OperationBoard({ data, canUpdateBookings, canUpdateRooms }: { data: DailyOperations; canUpdateBookings: boolean; canUpdateRooms: boolean }) {
  const locale = useLocale();
  return <>
    <div className="mt-8 grid gap-8 xl:grid-cols-2">
      <section><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-[-0.02em]">{localize(locale, "Kedatangan", "Arrivals")}</h2><p className="mt-2 text-sm text-muted">{localize(locale, "Tamu yang perlu disambut dan disiapkan akses kamarnya.", "Guests to welcome and provide room access.")}</p></div><span className="text-sm font-semibold tabular-nums text-secondary">{data.arrivals.length}</span></div><div className="mt-5 divide-y overflow-hidden rounded-lg bg-surface shadow-[0_18px_42px_-28px_rgba(68,71,72,.25)]">{data.arrivals.length ? data.arrivals.map((booking) => <BookingRow key={booking.id} booking={booking} kind="arrival" canUpdate={canUpdateBookings} />) : <Empty>{localize(locale, "Tidak ada kedatangan pada tanggal ini.", "No arrivals on this date.")}</Empty>}</div></section>
      <section><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-[-0.02em]">{localize(locale, "Keberangkatan", "Departures")}</h2><p className="mt-2 text-sm text-muted">{localize(locale, "Selesaikan masa inap dan teruskan kamar ke housekeeping.", "Complete stays and hand rooms over to housekeeping.")}</p></div><span className="text-sm font-semibold tabular-nums text-secondary">{data.departures.length}</span></div><div className="mt-5 divide-y overflow-hidden rounded-lg bg-surface shadow-[0_18px_42px_-28px_rgba(68,71,72,.25)]">{data.departures.length ? data.departures.map((booking) => <BookingRow key={booking.id} booking={booking} kind="departure" canUpdate={canUpdateBookings} />) : <Empty>{localize(locale, "Tidak ada keberangkatan pada tanggal ini.", "No departures on this date.")}</Empty>}</div></section>
    </div>
    <section className="mt-12 border-t pt-9"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold tracking-[-0.02em]">Housekeeping</h2><p className="mt-2 text-sm text-muted">{localize(locale, "Kamar menunggu pemeriksaan akhir sebelum dijual kembali.", "Rooms awaiting final inspection before becoming sellable again.")}</p></div><span className="text-sm font-semibold tabular-nums text-secondary">{data.housekeeping.length} {localize(locale, "kamar", data.housekeeping.length === 1 ? "room" : "rooms")}</span></div>{data.housekeeping.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.housekeeping.map((room) => <article key={room.id} className="flex min-h-36 flex-col justify-between rounded-lg bg-[#f2e8da] p-5 text-[#51391f]"><div><p className="text-xs font-semibold tracking-[0.08em] uppercase">{localize(locale, "Sedang dibersihkan", "Cleaning")}</p><h3 className="mt-2 text-xl font-semibold text-primary">{room.name}</h3></div>{canUpdateRooms && <div className="mt-5"><ConfirmAction action={markRoomReadyAction.bind(null, room.id)} trigger={localize(locale, "Tandai sudah siap", "Mark as ready")} title={localize(locale, `${room.name} sudah siap?`, `Is ${room.name} ready?`)} description={localize(locale, "Pastikan kamar telah dibersihkan, diperiksa, dan seluruh fasilitas berfungsi.", "Confirm the room is clean, inspected, and all amenities are working.")} confirmLabel={localize(locale, "Ya, kamar siap", "Yes, room is ready")} tone="primary" triggerVariant="primary" /></div>}</article>)}</div> : <div className="mt-5 border-y bg-surface py-12 text-center text-sm text-muted">{localize(locale, "Tidak ada kamar dalam antrean pembersihan.", "No rooms are waiting for cleaning.")}</div>}</section>
  </>;
}
